[libraries]
okio = { module = "com.squareup.okio:okio", version = "3.4.0" }

[plugins]
github-release = { id = "com.github.breadmoirai.github-release", version = "2.5.2" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.0" }
shadow-jar = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
spotbugs = { id = "com.github.spotbugs", version = "6.0.7" }
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
spring-boot = { id = "org.springframework.boot", version = "3.2.2" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.4" }
versions = { id = "com.github.ben-manes.versions", version = "0.51.0" }
